[workspace]

members = [
	"binding_ffi", "o_thi_offline_search"
]

[workspace.dependencies]
tokio = { version = "1.35.1", features = ["macros"] }
thiserror = "2.0.3"
o_thi_offline_search = { path = "o_thi_offline_search" }
