[workspace]

members = [
	"ermis_call_node_binding",  "ermis-call-node"
]

[workspace.dependencies]
tokio = { version = "1.35.1", features = ["macros"] }
thiserror = "2.0.3"
ermis-call-node = { path = "ermis-call-node" }